from enum import Enum


class MmkEndpoint(Enum):
    WORLD_REGIONS = "/worldRegions"
    COUNTRIES = "/countries"
    COUNTRY = "/country/{country_id}"
    WORLD_REGION = "/worldRegion/{world_region_id}"
    SAILING_AREAS = "/sailingAreas"
    SAILING_AREA = "/sailingArea/{sailing_area_id}"
    BASES = "/bases"
    BASE = "/base/{base_id}"
    EQUIPMENT = "/equipment"
    COMPANIES = "/companies"
    COMPANY = "/company/{company_id}"
    SHIPYARDS = "/shipyards"
    SHIPYARD = "/shipyard/{shipyard_id}"
    YACHT_TYPES = "/yachtTypes"
    YACHTS = "/yachts"
    YACHT = "/yacht/{yacht_id}"
    OFFERS = "/offers"
    SPECIAL_OFFERS = "/specialOffers"
    SPECIAL_OFFERS_BY_TYPE = "/specialOffers/{offer_type}"
    PRICES = "/prices"
    SET_WEEKLY_PRICES = "/setWeeklyPrices/{id}"
    RESERVATION_CREATE = "/reservation"
    RESERVATION_DETAILS = "/reservation/{reservation_id}"
    RESERVATION_LIST = "/reservations/{year}"
    AVAILABILITY = "/availability/{year}"
    SHORT_AVAILABILITY = "/shortAvailability/{year}"
    ADD_DOCUMENT = "/addDocument/{item_type}"
    CREW_LIST_LINK = "/crewListLink/{reservation_id}"
